#!/bin/bash

checkPostgres () {
  if [[ $(id -u postgres 2> /dev/null) = "" ]]; then
    echo "Parece que o postgres não está instalado!";
    echo "Execute: sudo apt update && sudo apt install postgresql postgresql-contrib";
    exit;
  fi

  if [[ $(pgrep -u postgres -fa -- -D) = "" ]]; then
    echo "PostgreSQL não está sendo executado, tentando iniciar...";
    sudo service postgresql start;
  fi
}

createDatabase () {
  sudo -i -u postgres psql -c "CREATE DATABASE $1;" ;
}

destroyDatabase () {
  sudo -i -u postgres psql -c "DROP DATABASE $1;";
}

enterPostgresCli () {
  sudo -i -u postgres psql -d $1;
}

createRole() {
  sudo -i -u postgres psql -c "
    CREATE ROLE $1 WITH SUPERUSER CREATEDB CREATEROLE LOGIN ENCRYPTED PASSWORD '123456';
  ";
}

restoreDatabase () {
  echo "Restaurando banco de dados...";
  sudo -i -u postgres psql -c "CREATE DATABASE $1;";
  sudo -i -u postgres psql $1 < ../$2;
}

createEnvVariables () {
  echo "Criando variáveis de ambiente...";

  echo "DB_USER=$1
        DB_PASSWORD=123456
        DB_PORT=5432
        DB_HOST=localhost
        DB_DATABASE=$2
        PORT=4000" > ../.env.development &&

  echo "DB_USER=$1
        DB_PASSWORD=123456
        DB_PORT=5432
        DB_HOST=localhost
        DB_DATABASE=$3
        PORT=4000" > ../.env.test;
}